// Generated by Skyramp v1.3.24 on 2026-05-13 00:02:44.256908575 +0000 UTC m=+304.780964333
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_view_empty_state.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_view_empty_state_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(193000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:8055/admin/login");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "password"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;


    const playwrightRequest1: Record<string, any> = {"password": "directus"};

    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest1, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest2: Record<string, any> = {"password": "admin"};

    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest2, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response2 = await responsePromise2;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    expect(response2.status()).toBe(200);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/notifications");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Notifications');
    await expect(page.getByText('No notifications', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'done_all' })).toBeDisabled();

    await page.getByRole("button", { name: "refresh" }).click();

    await expect(page.getByText('No notifications', { exact: true })).toBeVisible();
    expect(errors).toHaveLength(0);
});
