// Generated by Skyramp v1.3.23 on 2026-05-12 19:15:47.217731813 +0000 UTC m=+430.115774763
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_bell_panel.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_bell_panel_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(159000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8055/admin/content");
    await page.getByRole("textbox", { name: "Email" }).fill("admin@example.com");
    await page.getByRole("textbox", { name: "Password" }).fill("admin");
    await page.getByRole("button", { name: "Sign In" }).click();
    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.getByRole("button", { name: "notifications" }).click();
    await page.waitForTimeout(1500);
    await expect(page.getByRole("heading", { name: "Notifications", exact: true })).toHaveText("Notifications");
    await expect(page.getByRole("heading", { name: "No Notifications" })).toHaveText("No Notifications");
    await page.getByRole("button", { exact: true, name: "close" }).click();
    expect(pageErrors).toHaveLength(0);
});
