// Generated by Skyramp v1.3.23 on 2026-05-12 19:15:45.748001617 +0000 UTC m=+428.646044597
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_center_view.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/app/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/.skyramp/notifications_center_view_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(233000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8055");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Remind Later" }).click();
    await page.goto("http://localhost:8055/admin/notifications");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("heading", { name: "Notifications" })).toHaveText("Notifications");
    await expect(page.getByRole("paragraph")).toHaveText("No notifications");

    await page.getByRole("button", { name: "refresh" }).click();
    await page.waitForTimeout(1500);

    await expect(page.getByRole("paragraph")).toHaveText("No notifications");
    expect(pageErrors).toHaveLength(0);
});
