// Generated by Skyramp v1.3.24 on 2026-05-13 00:06:03.43216734 +0000 UTC m=+503.956223107
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output notifications_read_all_verify_me_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests/blackbox/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/directus/directus/tests/blackbox/api/scenario_notifications-read-all-verify-me.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const readAllPatchRequestBody = `{}`
    
    // Execute Request
    let readAllPatchResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/notifications/read-all",
        method:"PATCH",
        body:readAllPatchRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(readAllPatchResponse.statusCode, 'status code').toBe(200);
    expect(getValue(readAllPatchResponse, "data.updated"), 'updated count').toBe(0);
    expect(getValue(readAllPatchResponse, "data.updated"), 'updated range').toBeGreaterThanOrEqual(0);

    // Execute Request
    let meGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/users/me",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(meGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(meGetResponse, "data.unread_notifications"), 'unread_notifications').toBe(0);
    expect(getValue(meGetResponse, "data.unread_notifications"), 'unread_notifications range').toBeGreaterThanOrEqual(0);
    expect(getValue(meGetResponse, "data.id"), 'user id format').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
});

